language: generic

services: docker

cache:
  timeout: 900
  directories:
  - $HOME/cache

env:
  - IMAGE_TAGS="master-alpine-dev"                 IMAGE_DIRECTORY="master/alpine/dev"                 GIT_BRANCH="master"
  - IMAGE_TAGS="26.1-alpine-dev 26-alpine-dev alpine-dev" IMAGE_DIRECTORY="26.1/alpine/dev"                   GIT_BRANCH="emacs-26.1"
  - IMAGE_TAGS="25.3-alpine-dev 25-alpine-dev"     IMAGE_DIRECTORY="25.3/alpine/dev"                   GIT_BRANCH="emacs-25.3"
  - IMAGE_TAGS="25.2-alpine-dev"                   IMAGE_DIRECTORY="25.2/alpine/dev"                   GIT_BRANCH="emacs-25.2"
  - IMAGE_TAGS="25.1-dev"                          IMAGE_DIRECTORY="25.1/xenial/dev"                   GIT_BRANCH="emacs-25.1"
  - IMAGE_TAGS="24.5-dev 24-dev"                   IMAGE_DIRECTORY="24.5/xenial/dev"                   GIT_BRANCH="emacs-24.5"
  - IMAGE_TAGS="24.4-dev"                          IMAGE_DIRECTORY="24.4/precise/autogen/dev"          GIT_BRANCH="emacs-24.4"
  - IMAGE_TAGS="24.3-dev"                          IMAGE_DIRECTORY="24.3/precise/autogen/dev"          GIT_BRANCH="emacs-24.3"
  - IMAGE_TAGS="23.4-dev 23-dev"                   IMAGE_DIRECTORY="23.4/precise/bootstrap/dev"        GIT_BRANCH="emacs-23.4"

install:
  - source bin/setup-env
  - image-prepare "$GIT_REPOSITORY" "$GIT_BRANCH" "$TRAVIS_CACHE/emacs/$GIT_BRANCH" "$IMAGE_DIRECTORY"
  - docker-load-images "$TRAVIS_CACHE/docker/images.tar"
  - image-build "$DOCKER_REPOSITORY" "$IMAGE_TAGS" "$IMAGE_DIRECTORY"
  - image-push "$DOCKER_REPOSITORY" "$IMAGE_TAGS"
  - docker-save-images "$TRAVIS_CACHE/docker/images.tar"

notifications:
  email:
    on_success: never
    on_failure: never
