language: generic

services: docker

cache:
  timeout: 900
  directories:
    - $HOME/cache

env:
  - DOCKER_IMAGES="master-alpine-ci"
  - DOCKER_IMAGES="26.1-alpine-ci"
  - DOCKER_IMAGES="25.3-alpine-ci"
  - DOCKER_IMAGES="25.2-alpine-ci"
  - DOCKER_IMAGES="25.1-ci"
  - DOCKER_IMAGES="24.5-ci"
  - DOCKER_IMAGES="24.4-dev 24.4-ci"
  - DOCKER_IMAGES="24.3-dev 24.3-ci"
  - DOCKER_IMAGES="23.4-dev"

install:
  - source bin/setup-env
  - images prepare $DOCKER_IMAGES
  - images build $DOCKER_IMAGES
  - images test $DOCKER_IMAGES

after_success:
  - |
    # DOCKER_USERNAME is empty for forked repositories
    # TRAVIS_PULL_REQUEST is "true" for pull requests
    # TRAVIS_BRANCH is the current branch or the PR target branch
    # TRAVIS_PULL_REQUEST_BRANCH is the PR source branch
    github_branch="${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}"
    if [[ ! -z "$DOCKER_USERNAME" ]] && [[ "$TRAVIS_PULL_REQUEST" != "true" ]] && \
       [[ "$github_branch" == "master" ]] || [[ "$github_branch" == "staging-"* ]]; then
      images push $DOCKER_IMAGES
    else
      echo ">>> not pushing"
    fi

notifications:
  email:
    on_success: never
    on_failure: never
