language: generic

services: docker

cache:
  timeout: 900
  directories:
    - $HOME/cache

branches:
  only:
    - master

env:
{{ENV}}

install:
  - source bin/setup-env
  - travis_retry images prepare $DOCKER_IMAGES
  - travis_retry images build $DOCKER_IMAGES
  - images test $DOCKER_IMAGES

after_success:
  - |
    # DOCKER_USERNAME is empty for forked repositories
    # TRAVIS_PULL_REQUEST is "true" for pull requests
    # TRAVIS_BRANCH is the current branch or the PR target branch
    # TRAVIS_PULL_REQUEST_BRANCH is the PR source branch
    github_branch="${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}"
    if [[ ! -z "$DOCKER_USERNAME" ]] && [[ "$TRAVIS_PULL_REQUEST" != "true" ]] && \
       [[ "$github_branch" == "master" ]] || [[ "$github_branch" == "staging-"* ]]; then
      images push $DOCKER_IMAGES
    else
      echo ">>> not pushing"
    fi

notifications:
  email:
    on_success: never
    on_failure: never
